name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
      
      - name: Format check (Prettier)
        run: npm run format:check
        continue-on-error: false
        
      - name: Run type check
        run: npm run typecheck
        if: ${{ hashFiles('package.json') }}
        continue-on-error: false
      
      - name: Build project
        run: npm run build
