name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build

      - name: Install Lighthouse CI
        run: npm ci && npx --yes @lhci/cli@0.13.x --version

      - name: Start Next.js production server (background)
        run: |
          PORT=3000 nohup npm run start &>/dev/null &

      - name: Wait for server readiness
        run: npx wait-on http://127.0.0.1:3000

      - name: Run Lighthouse CI against running site
        run: npx lhci autorun --collect.url=http://127.0.0.1:3000 --collect.chromeFlags="--no-sandbox --disable-setuid-sandbox"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
